@echo off
echo Removing previous EF Migrations...
dotnet ef migrations remove
echo Running EF Migrations...
dotnet ef migrations add InitialCreate
echo Applying EF Migrations to the database...
dotnet ef database update
