echo What is the migration name?
read varname
echo Running EF Migrations for \($varname\)...
dotnet ef migrations add $varname
echo Applying EF Migrations to the database...
dotnet ef database update
